const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = [
    './view/root.js',
    './view/api/authentication.js',
    './view/api/message.js',
    './view/api/pokemon.js',
]


const doc = {
    info: {
        version: "1.0.0",
        title: "GeekMon API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Auth",
            "description": "Endpoints de autenticacion"
        },
        {
            "name": "Message",
            "description": "Endpoints de administracion de los mensajes del foro"
        },
        {
            "name": "Pokemon",
            "description": "Endpoints sobre interaccion con los pokemon"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "Bearer",
            name: "Authorization",
            in: "header"
        },
    },
    definitions: {
        User: {
            username: "Jhon Doe",
            password: "djnsifnsanli",
            role: "member"
        },
        Token: {
            userId: "1234",
            token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzA4MDc5MTMsImV4cCI6MTY3MzM5OTkxM30.pr6RclyYIIXo55m3myAuE_Mi_fdQVuDJj3VntZhOxxg"
        }
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})